Start assignment
ShaunWMusic/10-twitch pull request #1
Opened 2016-10-13 20:46 UTC by ShaunWMusic

2016-10-13 20:46 UTC, ShaunWMusic commented
* [ ] Fork Repository `tiy-tn-fee-2016-fall/10-twitch` on Github
* [ ] Run `hub clone 10-twitch` to clone your repo locally
* [ ] Run `npm install` in project directory to install test and build dependencies
* [ ] Run `hub remote add class tiy-tn-fee-2016-fall/10-twitch` so that you can pull new changes as they come
* [ ] Create `develop` branch

2016-10-13 20:46 UTC, ShaunWMusic commented
* [ ] Work through tests for '01-create-message-item'
* [ ] Work through tests for '02-add-message-item'
* [ ] Work through tests for '03-sum-from-list'
* [ ] Work through tests for '04-reverse-list'

2016-10-13 20:46 UTC, ShaunWMusic commented
* [ ] Run `git pull --no-edit class master` to bring in updates to the assignment
* [ ] Look at the tests in the `tests/twitch` folder
  * [ ] Work through tests for '01-create-game-item'
  * [ ] Work through tests for '02-add-games-to-list'
  * [ ] Work through tests for '03-search-twitch'
* [ ] Run `git pull --no-edit class master` to bring in updates to the assignment
* [ ] Write HTML for the Twitch left sidebar
* [ ] Style the Twitch left sidebar
* [ ] Write HTML for the Twitch right sidebar
* [ ] Style the Twitch right sidebar
* [ ] Style the game results

2016-10-23 02:01 UTC, rtablada requested changes

2016-10-23 02:01 UTC, rtablada commented on app/index.js
> +<<<<<<< HEAD
Looks like you committed merge conflicts. Remove this line that says `HEAD` all the way through the `=======`.

2016-10-23 02:01 UTC, rtablada commented on app/index.js
> +>>>>>>> eb1ab13731653051706223d3532d706ecdfac751
Then remove this line which is showing the end of changes for things that you merged in from my branch.

2017-03-09 23:25 UTC, merged